# Generated by Django 4.0.1 on 2022-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='rate',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='load',
            name='total_km',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='load',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
