# Generated by Django 4.0.1 on 2022-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_load_rate_load_total_km_alter_load_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='rate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_km',
            field=models.CharField(default='', max_length=255),
        ),
    ]
